### ISSUE TITLE
beta release

### ISSUE THREAD

**Issue by heytitle** [PyThaiNLP/attacut#1]
# Tasks
- [x] make it pipable
- [x] use logger instead of `print`
- [x] add more test
- [x] add linting
- [x] refactor training.py
- ~~[ ] batch processing  for `attacut-cli`~~ (moved to #5)

# Documentations (now available on https://pythainlp.github.io/attacut)
- [x] how to train a new model
- [x] module overview in this repo

# 

# Testing & Final Benchmark
- [x] install via `pip`
- [x] run tokenization to check whether the implement is correctly migrated.
- [x] testing speed
- [x] update visualisation results

**Comment by wannaphongcom** [comment]
@heytitle You can release a pre-release versions in PyPI. https://pip.pypa.io/en/stable/reference/pip_install/#pre-release-versions

**Comment by heytitle** [comment]
@wannaphongcom thanks for the recommendation. Now you can install it via
```
$ pip install attacut
```
Noting here that, you don't have to specify `--pre` here because we only have pre-release versions there and `pip` will just pick the latest pre-release version ([REF][ref])


[ref]: https://github.com/pypa/pip/issues/5503#issuecomment-397406934
